version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.production
    env_file: .env
    profiles:
      - "api"
    environment:
      DEV_DATABASE_USER: root
      DEV_DATABASE_PASSWORD: Ra19271996
      DEV_DATABASE_HOST: postgres
      DEV_DATABASE: postgres
    ports:
      - "5000:5000"
      - "9229:9229"
    volumes:
      - ./:/usr/app
    depends_on:
      - postgres
    container_name: "backend"
    networks:
      - backend-network

  postgres:
    image: "postgres"
    profiles:
      - "db"
      - "api"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: Ra19271996
    ports:
      - "5432:5432"
    container_name: "backend_postgres"
    networks:
      - backend-network

volumes:
  pgdata:
    driver: local

networks:
  backend-network:
